version: '3.7'
services:
  mysql_db:
    image: mysql:5.6
    container_name: mysql_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: New
      TZ: Asia/Bangkok
    networks:
      - default  

networks:
  default:
    driver: bridge

volumes:
  db_data:    
  